export const All_PRODUCTS_REQUEST = 'All_PRODUCTS_REQUEST '
export const All_PRODUCTS_SUCCESS = 'All_PRODUCTS_SUCCESS '
export const All_PRODUCTS_FAIL = 'All_PRODUCTS_FAIL '

export const PRODUCTS_DETAILS_REQUEST = 'All_PRODUCTS_REQUEST '
export const PRODUCTS_DETAILS_SUCCESS = 'PRODUCTS_DETAILS_SUCCESS '
export const PRODUCTS_DETAILS_FAIL = 'PRODUCTS_DETAILS_FAIL '

export const CLEAR_ERRORS = 'CLEAR_ERRORS '